name: project with cicd pointer

on:
  push:
    branches: [ "pointer" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -f survey/pom.xml  clean install
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
            image: moin2391/survey
            tags: latest
            registry: docker.io
            dockerfile: survey/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
  deploy:
   needs : build
   runs-on : [momin]
   steps :
     - name : pull image from docker hub
       run : sudo docker pull moinmomin/ss
     - name : delete old identation 
       run : sudo docker rm -f moin
     - name : run container
       run : docker run -p 8080:8080 --name moin moinmomin/ss
