name: CI/CD for Spring Boot on Minikube

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
     - name: Build with Maven
       run: mvn -f survey/pom.xml  clean install
     - name: Build & push Docker image
       uses: mr-smithers-excellent/docker-build-push@v5
       with:
            image: moin2391/survey
            tags: latest
            registry: docker.io
            dockerfile: survey/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    name: Deploy to Minikube
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Minikube
        run: |
          minikube start --vm-driver=docker
          minikube kubectl -- get pods -A
          minikube kubectl -- create deployment my-app --image=moin2391/survey
          minikube kubectl -- expose deployment my-app --type=LoadBalancer --port=8080
          minikube kubectl -- get services
